import icons from '../helper/icons'

export const MaterialItems = [
  {
    imageUrl: "/home/featuredBoxes/bakery-boxes.webp",
    name: "Bakery Boxes",
    href: "/categories/bakery-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/candle-boxes.webp",
    name: "Candle Boxes",
    href: "/categories/candle-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/candy-boxes.webp",
    name: "Candy Boxes",
    href: "/categories/candy-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/chocolate-Boxes.webp",
    name: "Chocolate Boxes",
    href: "/categories/chocolate-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/christmas-boxes.webp",
    name: "Christmas Boxes",
    href: "/categories/christmas-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/Cosmetic-Boxes.webp",
    name: "Cosmetic Boxes",
    href: "/categories/cosmetic-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/food-boxes.webp",
    name: "Food Boxes",
    href: "/categories/food-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/gable-boxes.webp",
    name: "Gable Boxes",
    href: "/categories/gable-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/gift-boxes.webp",
    name: "Gift Boxes",
    href: "/categories/gift-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/kraft-boxes.webp",
    name: "Kraft Boxes",
    href: "/categories/kraft-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/mylar-bags.webp",
    name: "Mylar Bags",
    href: "/categories/mylar-bags",
  },
  {
    imageUrl: "/home/featuredBoxes/paper-coffee-kraft-bags.webp",
    name: "Coffee Bags",
    href: "/categories/coffee-bags",
  },
  {
    imageUrl: "/home/featuredBoxes/pillow-boxes.webp",
    name: "Pillow Boxes",
    href: "/categories/pillow-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/rigid-boxes.webp",
    name: "Rigid Boxes",
    href: "/categories/rigid-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/rigid-sleeve-and-tray-boxes.webp",
    name: "Sleeve Tray Boxes",
    href: "/categories/sleeve-tray-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/soap-boxes.webp",
    name: "Soap Boxes",
    href: "/categories/soap-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/tea-packaging.webp",
    name: "Tea Boxes",
    href: "/categories/tea-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/tin-boxes.webp",
    name: "Tin Boxes",
    href: "/categories/tin-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/tuck-boxes.webp",
    name: "Tuck Boxes",
    href: "/categories/tuck-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/window-box.webp",
    name: "Window Boxes",
    href: "/categories/window-boxes",
  },
];

export const IndustryItems = [
  { name: "Food & Beverage", icon: icons.IoFastFoodOutline },
  { name: "Pharmaceutical", icon: icons.IoMedicalOutline },
  { name: "Cosmetics & Beauty", icon: icons.IoFlowerOutline },
  { name: "Electronics", icon: icons.MdOutlineDesignServices },
  { name: "Retail & Apparel", icon: icons.IoShirtOutline },
  { name: "Gift & Luxury", icon: icons.IoGiftOutline },
  { name: "E-commerce & Shipping", icon: icons.MdOutlineLocalShipping },
  { name: "Healthcare & Medical", icon: icons.IoMedicalOutline },
  { name: "Automotive", icon: icons.GiCarWheel },
  { name: "Industrial & Machinery", icon: icons.GiFactoryArm },
  { name: "Toys & Games", icon: icons.GiGamepad },
  { name: "Books & Publishing", icon: icons.GiBookCover },
  { name: "Office Supplies", icon: icons.GiNotebook },
  { name: "Jewelry & Watches", icon: icons.GiGemNecklace },
  { name: "Pet Supplies", icon: icons.GiDogBowl },
  { name: "Home & Kitchen", icon: icons.GiKitchenScale },
  { name: "Sports & Fitness", icon: icons.GiSportMedal },
  { name: "Agriculture", icon: icons.GiWheat },
  { name: "Floral", icon: icons.GiFlowerPot },
  { name: "Military & Defense", icon: icons.GiAmmoBox },
  { name: "Aerospace", icon: icons.GiJetPack },
  { name: "Art & Crafts", icon: icons.GiPaintBrush },
  { name: "Musical Instruments", icon: icons.GiGuitarHead },
  { name: "Event & Wedding", icon: icons.GiPartyFlags },
  { name: "Educational", icon: icons.GiGraduateCap },
  { name: "Recycling & Waste", icon: icons.GiRecycle },
  { name: "Construction", icon: icons.GiBrickWall },
  { name: "Marine & Fishing", icon: icons.GiFishingBoat },
];

export const StyleItems = [
  { name: "Regular Slotted Container (RSC)", icon: icons.GiCardboardBoxClosed },
  { name: "Full Overlap Box (FOL)", icon: icons.GiCardboardBox },
  { name: "Half-Slotted Container (HSC)", icon: icons.GiCardboardBox },
  { name: "Mailer Boxes", icon: icons.MdOutlineMail },
  { name: "Display Boxes", icon: icons.MdOutlineWindow },
  { name: "Tuck Top Boxes", icon: icons.MdOutlineFeaturedPlayList },
  { name: "Gable Boxes", icon: icons.IoGiftOutline },
  { name: "Drawer Boxes", icon: icons.MdOutlineInventory2 },
  { name: "Telescoping Boxes", icon: icons.GiCardboardBox },
  { name: "Five Panel Folder", icon: icons.GiCardboardBox },
  { name: "Rigid Boxes", icon: icons.GiWoodenCrate },
  // { name: "Clamshell Boxes", icon: FishSymbol },
  { name: "Book Style Boxes", icon: icons.GiBookCover },
  { name: "Jewelry Boxes", icon: icons.GiGemNecklace },
  { name: "Takeout Boxes", icon: icons.MdOutlineTakeoutDining },
  { name: "Pizza Boxes", icon: icons.GiPizzaCutter },
  { name: "Bakery Boxes", icon: icons.GiCroissant },
  { name: "Bulk Shipping Boxes", icon: icons.MdOutlineLocalShipping },
  { name: "Wardrobe Boxes", icon: icons.GiClothes },
  { name: "Tube Boxes", icon: icons.GiRolledCloth },
  { name: "Custom Printed Boxes", icon: icons.MdOutlineDesignServices },
  { name: "Window Cutout Boxes", icon: icons.MdOutlineWindow },
  { name: "Die-Cut Boxes", icon: icons.GiScissors },
  { name: "Hexagonal Boxes", icon: icons.GiHexes },
  { name: "Folding Cartons", icon: icons.GiCardboardBox },
  { name: "Pop-Up Boxes", icon: icons.GiPresent },
  { name: "Magnetic Closure Boxes", icon: icons.GiMagnet },
  { name: "Recyclable Boxes", icon: icons.GiRecycle },
  { name: "Compostable Boxes", icon: icons.GiLeafSwirl },
];

export const materialItems = [
  { name: "Corrugated Cardboard", icon: icons.GiCardboardBox },
  { name: "Kraft Paper", icon: icons.GiBookCover },
  { name: "Rigid Board", icon: icons.GiWoodenCrate },
  { name: "Recycled Materials", icon: icons.GiRecycle },
  { name: "Bubble Wrap", icon: icons.GiPresent },
  { name: "Foam Inserts", icon: icons.GiMagnet },
  { name: "Biodegradable", icon: icons.GiLeafSwirl },
  { name: "Plastic-Free", icon: icons.GiRecycle },
  { name: "FSC Certified", icon: icons.GiWheat },
  { name: "Food-Grade", icon: icons.IoFastFoodOutline },
  { name: "Water-Resistant", icon: icons.GiFishingBoat },
  { name: "Reusable", icon: icons.GiRecycle },
];
