import {
  IoFastFoodOutline,
  IoFlowerOutline,
  IoGiftOutline,
  IoMedicalOutline,
  IoShirtOutline,
} from "react-icons/io5";
import {
  GiCardboardBox,
  GiPizzaCutter,
  GiCroissant,
  GiScissors,
  GiHexes,
  GiPresent,
  GiMagnet,
  GiLeafSwirl,
  GiWoodenCrate,
  GiBookCover,
  GiGemNecklace,
  GiClothes,
  GiRolledCloth,
  GiRecycle,
  GiCarWheel,
  GiGamepad,
  GiFactoryArm,
  GiNotebook,
  GiDogBowl,
  GiKitchenScale,
  GiSportMedal,
  GiAmmoBox,
  GiBrickWall,
  GiFishingBoat,
  GiFlowerPot,
  GiGraduateCap,
  GiGuitarHead,
  GiJetPack,
  GiPaintBrush,
  GiPartyFlags,
  GiWheat,
  GiCardboardBoxClosed,
} from "react-icons/gi";
import {
  MdOutlineDesignServices,
  MdOutlineFeaturedPlayList,
  MdOutlineInventory2,
  MdOutlineLocalShipping,
  MdOutlineMail,
  MdOutlineTakeoutDining,
  MdOutlineWindow,
} from "react-icons/md";

export const MaterialItems = [
  {
    imageUrl: "/home/featuredBoxes/bakery-boxes.webp",
    name: "Bakery Boxes",
    href: "/categories/bakery-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/candle-boxes.webp",
    name: "Candle Boxes",
    href: "/categories/candle-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/candy-boxes.webp",
    name: "Candy Boxes",
    href: "/categories/candy-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/chocolate-Boxes.webp",
    name: "Chocolate Boxes",
    href: "/categories/chocolate-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/christmas-boxes.webp",
    name: "Christmas Boxes",
    href: "/categories/christmas-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/Cosmetic-Boxes.webp",
    name: "Cosmetic Boxes",
    href: "/categories/cosmetic-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/food-boxes.webp",
    name: "Food Boxes",
    href: "/categories/food-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/gable-boxes.webp",
    name: "Gable Boxes",
    href: "/categories/gable-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/gift-boxes.webp",
    name: "Gift Boxes",
    href: "/categories/gift-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/kraft-boxes.webp",
    name: "Kraft Boxes",
    href: "/categories/kraft-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/mylar-bags.webp",
    name: "Mylar Bags",
    href: "/categories/mylar-bags",
  },
  {
    imageUrl: "/home/featuredBoxes/paper-coffee-kraft-bags.webp",
    name: "Coffee Bags",
    href: "/categories/coffee-bags",
  },
  {
    imageUrl: "/home/featuredBoxes/pillow-boxes.webp",
    name: "Pillow Boxes",
    href: "/categories/pillow-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/rigid-boxes.webp",
    name: "Rigid Boxes",
    href: "/categories/rigid-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/rigid-sleeve-and-tray-boxes.webp",
    name: "Sleeve Tray Boxes",
    href: "/categories/sleeve-tray-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/soap-boxes.webp",
    name: "Soap Boxes",
    href: "/categories/soap-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/tea-packaging.webp",
    name: "Tea Boxes",
    href: "/categories/tea-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/tin-boxes.webp",
    name: "Tin Boxes",
    href: "/categories/tin-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/tuck-boxes.webp",
    name: "Tuck Boxes",
    href: "/categories/tuck-boxes",
  },
  {
    imageUrl: "/home/featuredBoxes/window-box.webp",
    name: "Window Boxes",
    href: "/categories/window-boxes",
  },
];

export const IndustryItems = [
  { name: "Food & Beverage", icon: IoFastFoodOutline },
  { name: "Pharmaceutical", icon: IoMedicalOutline },
  { name: "Cosmetics & Beauty", icon: IoFlowerOutline },
  { name: "Electronics", icon: MdOutlineDesignServices },
  { name: "Retail & Apparel", icon: IoShirtOutline },
  { name: "Gift & Luxury", icon: IoGiftOutline },
  { name: "E-commerce & Shipping", icon: MdOutlineLocalShipping },
  { name: "Healthcare & Medical", icon: IoMedicalOutline },
  { name: "Automotive", icon: GiCarWheel },
  { name: "Industrial & Machinery", icon: GiFactoryArm },
  { name: "Toys & Games", icon: GiGamepad },
  { name: "Books & Publishing", icon: GiBookCover },
  { name: "Office Supplies", icon: GiNotebook },
  { name: "Jewelry & Watches", icon: GiGemNecklace },
  { name: "Pet Supplies", icon: GiDogBowl },
  { name: "Home & Kitchen", icon: GiKitchenScale },
  { name: "Sports & Fitness", icon: GiSportMedal },
  { name: "Agriculture", icon: GiWheat },
  { name: "Floral", icon: GiFlowerPot },
  { name: "Military & Defense", icon: GiAmmoBox },
  { name: "Aerospace", icon: GiJetPack },
  { name: "Art & Crafts", icon: GiPaintBrush },
  { name: "Musical Instruments", icon: GiGuitarHead },
  { name: "Event & Wedding", icon: GiPartyFlags },
  { name: "Educational", icon: GiGraduateCap },
  { name: "Recycling & Waste", icon: GiRecycle },
  { name: "Construction", icon: GiBrickWall },
  { name: "Marine & Fishing", icon: GiFishingBoat },
];

export const StyleItems = [
  { name: "Regular Slotted Container (RSC)", icon: GiCardboardBoxClosed },
  { name: "Full Overlap Box (FOL)", icon: GiCardboardBox },
  { name: "Half-Slotted Container (HSC)", icon: GiCardboardBox },
  { name: "Mailer Boxes", icon: MdOutlineMail },
  { name: "Display Boxes", icon: MdOutlineWindow },
  { name: "Tuck Top Boxes", icon: MdOutlineFeaturedPlayList },
  { name: "Gable Boxes", icon: IoGiftOutline },
  { name: "Drawer Boxes", icon: MdOutlineInventory2 },
  { name: "Telescoping Boxes", icon: GiCardboardBox },
  { name: "Five Panel Folder", icon: GiCardboardBox },
  { name: "Rigid Boxes", icon: GiWoodenCrate },
  // { name: "Clamshell Boxes", icon: FishSymbol },
  { name: "Book Style Boxes", icon: GiBookCover },
  { name: "Jewelry Boxes", icon: GiGemNecklace },
  { name: "Takeout Boxes", icon: MdOutlineTakeoutDining },
  { name: "Pizza Boxes", icon: GiPizzaCutter },
  { name: "Bakery Boxes", icon: GiCroissant },
  { name: "Bulk Shipping Boxes", icon: MdOutlineLocalShipping },
  { name: "Wardrobe Boxes", icon: GiClothes },
  { name: "Tube Boxes", icon: GiRolledCloth },
  { name: "Custom Printed Boxes", icon: MdOutlineDesignServices },
  { name: "Window Cutout Boxes", icon: MdOutlineWindow },
  { name: "Die-Cut Boxes", icon: GiScissors },
  { name: "Hexagonal Boxes", icon: GiHexes },
  { name: "Folding Cartons", icon: GiCardboardBox },
  { name: "Pop-Up Boxes", icon: GiPresent },
  { name: "Magnetic Closure Boxes", icon: GiMagnet },
  { name: "Recyclable Boxes", icon: GiRecycle },
  { name: "Compostable Boxes", icon: GiLeafSwirl },
];

export const materialItems = [
  { name: "Corrugated Cardboard", icon: GiCardboardBox },
  { name: "Kraft Paper", icon: GiBookCover },
  { name: "Rigid Board", icon: GiWoodenCrate },
  { name: "Recycled Materials", icon: GiRecycle },
  { name: "Bubble Wrap", icon: GiPresent },
  { name: "Foam Inserts", icon: GiMagnet },
  { name: "Biodegradable", icon: GiLeafSwirl },
  { name: "Plastic-Free", icon: GiRecycle },
  { name: "FSC Certified", icon: GiWheat },
  { name: "Food-Grade", icon: IoFastFoodOutline },
  { name: "Water-Resistant", icon: GiFishingBoat },
  { name: "Reusable", icon: GiRecycle },
];
