import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Poppins } from "next/font/google";
import ApolloWrapper from "@/helper/ApolloProvider";
import LoadCurrentUser from "@/components/LoadCurrentUser";
import { Providers } from "@/redux/providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
        <ApolloWrapper>
          <LoadCurrentUser />
          <Header />
          {children}
          <Footer />
        </ApolloWrapper>
        </Providers>
      </body>
    </html>
  );
}
